name: Android App Debug and Test Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    name: Build and Debug Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build debug APK
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
  test:
    name: Test Android App
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-debug
      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: adb install app-debug/app-debug.apk
      - name: Run Instrumented Tests
        run: ./gradlew connectedCheck
